import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

import { POLICY_ENVIRONMENT_ROUTES } from "../src/bash/policy-environment.js";
import { GH_HELP_TOPIC_RULES, GH_READ_ONLY_RULES } from "../src/bash/policies/gh-read-only.js";
import { ghNativeAliasesForRule } from "../src/bash/handlers/gh-command-line.js";

interface Fixture {
  readonly metadata: Readonly<Record<string, string>>;
  readonly commands: readonly {
    readonly path: readonly string[];
    readonly usage: string;
    readonly summary: string;
    readonly aliases: readonly (readonly string[])[];
    readonly kind: string;
    readonly preview: boolean;
  }[];
  readonly helpTopics: readonly { readonly name: string; readonly summary: string }[];
  readonly environment: readonly { readonly name: string }[];
  readonly dynamicRoutes: readonly { readonly kind: string; readonly route: string; readonly rationale: string }[];
}

export function renderGhReadOnlyAudit(fixture: Fixture): string {
  const rules = new Map(GH_READ_ONLY_RULES.map((rule) => [rule.path.join(" "), rule]));
  const lines: string[] = [
    "# GitHub CLI read-only command audit",
    "",
    "> Generated by `scripts/render-gh-read-only-audit.ts`. Do not edit this file directly.",
    "",
    "## Trust boundary",
    "",
    `This audit targets GitHub CLI **${fixture.metadata.version}**, upstream tag \`${fixture.metadata.tag}\` at commit \`${fixture.metadata.commit}\`.`,
    `The independent reference was captured on ${fixture.metadata.capturedAt}; its fixture checksum is \`${fixture.metadata.fixtureSha256}\`.`,
    "",
    "`ghReadOnly` is credential-safe, not a blanket non-mutating policy. GitHub CLI 2.100.0 performs configuration migration, update-check setup, and telemetry setup before dispatching commands, so this audit currently auto-allows no `gh` invocation. Commands that can mutate state, display unrestricted local or remote content, write files, download data, prompt, emit unreviewed terminal output, or invoke external programs also defer to the harness permission prompt.",
    "",
    "Unknown paths, options, abbreviations, configured aliases, installed extensions, malformed syntax, and unsupported output modes always defer. `gh api` remains owned by `ghApiReadOnly`; native `gh pr create` and `gh pr new` remain owned by `ghPrCreate` when that profile is enabled.",
    "`ghApiReadOnly` still denies mutating methods, and `ghPrCreate` still blocks non-allowlisted targets and unsafe forms, but neither profile auto-allows an invocation: owned reads and allowlisted creation remain prompt-gated because GitHub CLI startup can migrate configuration, access credential storage, check for updates, and launch telemetry before dispatch. Pager and prompt controls remain necessary but are not sufficient startup proofs.",
    "",
    "The deployed `gh` implementation is a trust assumption: runtime policy cannot detect behavior changes behind a known path in a future CLI. Any version upgrade requires fixture regeneration, policy review, documentation regeneration, unit/property tests, packaged runtime checks, and a new adversarial review.",
    "",
    "## Command classifications",
    "",
    "| Canonical command | Native aliases | Disposition | Exact auto-allowed form / owner | Excluded forms and rationale | Output trust | Relevant environment | Evidence |",
    "| --- | --- | --- | --- | --- | --- | --- | --- |",
  ];

  for (const entry of fixture.commands) {
    const key = entry.path.join(" ");
    const rule = rules.get(key);
    if (!rule) throw new Error(`missing manifest rule for gh ${key}`);
    const nativeAliases = ghNativeAliasesForRule(rule);
    const aliases = nativeAliases.length > 0 ? nativeAliases.map((alias) => `\`gh ${alias.join(" ")}\``).join(", ") : "None";
    const exact = rule.disposition === "allow"
      ? `\`gh ${key}\` only; zero flags and zero operands`
      : rule.disposition === "owned"
        ? `Owned by \`${rule.owner}\``
        : "None";
    const excluded = rule.disposition === "allow"
      ? "All flags, operands, redirects, and non-native spellings defer."
      : rule.disposition === "owned"
        ? "ghReadOnly does not authorize this route."
        : `${rule.exclusionReason}: ${rule.rationale}`;
    lines.push(`| \`gh ${escapeCell(key)}\` | ${aliases} | **${rule.disposition}**${rule.preview ? " (preview)" : ""} | ${escapeCell(exact)} | ${escapeCell(excluded)} | ${escapeCell(rule.outputTrust)} | ${escapeCell(rule.environmentRoutes.map((name) => `\`${name}\``).join(", ") || "None")} | ${escapeCell(rule.evidence)} |`);
  }

  lines.push(
    "",
    "## Root forms",
    "",
    "`gh --version`, `gh --help`, and bare `gh` defer. They use the same common startup path as subcommands, and unsupported flags or operands also defer.",
    "",
    "## Help topics",
    "",
    "True help topics are directly invokable hidden routes as well as `gh help <topic>` forms. Hidden executable commands such as `accessibility` and `actions` are tracked in the command inventory instead.",
    "",
    "| Topic | Disposition | Exact forms | Rationale |",
    "| --- | --- | --- | --- |",
  );
  for (const rule of GH_HELP_TOPIC_RULES) {
    lines.push(`| \`${rule.name}\` | **${rule.disposition}** | \`gh ${rule.name}\`, \`gh help ${rule.name}\` | ${escapeCell(rule.rationale)} |`);
  }

  const topLevel = fixture.commands.filter((entry) => entry.kind === "top-level-command");
  const hidden = fixture.commands.filter((entry) => entry.kind === "hidden-command");
  lines.push(
    "",
    "## Top-level-only commands",
    "",
    topLevel.map((entry) => `- \`gh ${entry.path.join(" ")}\`: ${entry.summary}`).join("\n"),
    "",
    "## Hidden executable commands",
    "",
    hidden.map((entry) => `- \`gh ${entry.path.join(" ")}\`: ${entry.summary}`).join("\n"),
    "",
    "## Preview commands",
    "",
    "Preview routes require re-review whenever upstream behavior changes:",
    "",
    fixture.commands.filter((entry) => entry.preview).map((entry) => `- \`gh ${entry.path.join(" ")}\``).join("\n"),
    "",
    "## Dynamic aliases and extensions",
    "",
    "These routes are not native built-ins and never normalize to a manifest command:",
    "",
  );
  for (const route of fixture.dynamicRoutes) lines.push(`- **${route.kind}** \`${route.route}\`: ${route.rationale}`);

  lines.push(
    "",
    "## Environment routes",
    "",
    "Authentication variables are listed for completeness but their values are never captured by policy analysis. The filtered snapshot explicitly records reviewed absent names as unset while every other omitted name remains unknown; present empty values remain explicit empty strings; non-empty defer-causing routes prevent automatic approval; unavailable or dynamically tainted values defer. Captured values are never included in evidence or diagnostics.",
    "",
    "| Variable | Classification | Scope | Captured | Decision |",
    "| --- | --- | --- | --- | --- |",
  );
  for (const route of POLICY_ENVIRONMENT_ROUTES) {
    lines.push(`| \`${route.name}\` | ${route.disposition} | ${route.scope} | ${route.capture ? "yes" : "no"} | ${escapeCell(route.rationale)} |`);
  }

  lines.push(
    "",
    "## Upgrade workflow",
    "",
    "1. Install and pin the new GitHub CLI version and upstream commit.",
    "2. Run `bun run scripts/capture-gh-cli-reference.ts --gh /absolute/path/to/gh` in an isolated environment.",
    "3. Review every added, removed, changed, hidden, preview, alias, and environment route.",
    "4. Update the typed manifest and exact grammars; unknown behavior remains deferred.",
    "5. Regenerate this document and run focused tests, the full Bun suite, packaged adapter checks, `nix flake check 'path:.'`, and `git diff --check`.",
    "6. Complete a frontier-model adversarial review and resolve every Critical and High finding.",
  );
  return `${lines.join("\n")}\n`;
}

if (import.meta.main) {
  const fixturePath = resolve(process.argv[2] ?? "data/gh-cli-2.100.0-reference.json");
  const outputPath = resolve(process.argv[3] ?? "docs/gh-read-only-command-audit.md");
  const fixture = JSON.parse(readFileSync(fixturePath, "utf8")) as Fixture;
  writeFileSync(outputPath, renderGhReadOnlyAudit(fixture));
}

function escapeCell(value: string): string {
  return value.replaceAll("|", "\\|").replaceAll("\n", " ");
}
